source "http://rubygems.org"

ruby '1.9.3'

gem "thin"
gem "sinatra"
gem "rsruby-heroku", :git => 'https://github.com/logical42/rsruby-heroku.git', :branch => 'master'
gem "foreman", :group => :development
